<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>UG/NX 二次开发(C#)自动出2D零件图思路 - 编程随想</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="UG/NX 二次开发(C#)自动出2D零件图思路" />
<meta property="og:description" content="一、前言 项目需要自动出2D零件图，可是我之前没做过这方面的内容，没有一点思路。然后我就做了下面几件事：
1、百度、google翻了一遍，搜索关键字“UG二次开发自动出图”
2、csdn.com 和 cnblogs.com翻了一遍
3、平时逛的qq技术群，微信技术群问候了一遍
4、做二开之后结交的技术大牛、小达人请教了一遍
现在有了一点思路，整理出来，自己也写了一部分主要源码分享出来供大家欣赏。
二、思路整理 自动出图方案经过我一番辛苦整理后，需要完成以下几步：
1、出图方案设置
出图方式千千万，每个人都有自己的想法，我们需要先定一个标准，然后程序才能按照标准自动出图，标准如下：
1）图纸参数设置，包括图纸类型，视图比例，图纸名称
2）视图布局方案，根据用户需求对视图进行布局，视图包括：顶视图、左视图、右视图、后视图、底视图、正三轴视图、右剖视图、底剖视图。
3）标注方案，目前我想到的先从简单的平面尺寸开始，先做水平、垂直、角度的标注
2、自动创建图纸、自动创建视图
3、自动标注
三、已完成部分源码分享 1、创建图纸
/// &lt;summary&gt; /// 创建图纸 /// &lt;/summary&gt; /// &lt;param name=&#34;workPart&#34;&gt;&lt;/param&gt; /// &lt;returns&gt;&lt;/returns&gt; public static Tag CreatDWG(Part workPart,string sheetName) { NXOpen.Drawings.DrawingSheet nullDrawings_DrawingSheet = null; NXOpen.Drawings.DrawingSheetBuilder drawingSheetBuilder1; drawingSheetBuilder1 = workPart.DrawingSheets.DrawingSheetBuilder(nullDrawings_DrawingSheet); drawingSheetBuilder1.StandardMetricScale = NXOpen.Drawings.DrawingSheetBuilder.SheetStandardMetricScale.S11; drawingSheetBuilder1.EnglishSheetTemplateLocation = &#34;&#34;; drawingSheetBuilder1.Height = 297.0; drawingSheetBuilder1.Length = 420.0; drawingSheetBuilder1.StandardMetricScale = NXOpen.Drawings.DrawingSheetBuilder.SheetStandardMetricScale.S11; drawingSheetBuilder1.StandardEnglishScale = NXOpen.Drawings.DrawingSheetBuilder.SheetStandardEnglishScale.S11; drawingSheetBuilder1.ScaleNumerator = 1.0; drawingSheetBuilder1.ScaleDenominator = 1." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/posts/eaa141d4028d6688b831672e0ee07e41/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-01-10T17:20:31+08:00" />
<meta property="article:modified_time" content="2023-01-10T17:20:31+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程随想" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程随想</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">UG/NX 二次开发(C#)自动出2D零件图思路</h1>
			
		</header>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <h2>一、前言</h2> 
<p>项目需要自动出2D零件图，可是我之前没做过这方面的内容，没有一点思路。然后我就做了下面几件事：</p> 
<p>1、百度、google翻了一遍，搜索关键字“UG二次开发自动出图”</p> 
<p>2、csdn.com 和 cnblogs.com翻了一遍</p> 
<p>3、平时逛的qq技术群，微信技术群问候了一遍</p> 
<p>4、做二开之后结交的技术大牛、小达人请教了一遍</p> 
<p>现在有了一点思路，整理出来，自己也写了一部分主要源码分享出来供大家欣赏。</p> 
<h2>二、思路整理</h2> 
<p>自动出图方案经过我一番辛苦整理后，需要完成以下几步：</p> 
<p>1、出图方案设置</p> 
<p>     出图方式千千万，每个人都有自己的想法，我们需要先定一个标准，然后程序才能按照标准自动出图，标准如下：</p> 
<p>      1）图纸参数设置，包括图纸类型，视图比例，图纸名称</p> 
<p>      2）视图布局方案，根据用户需求对视图进行布局，视图包括：顶视图、左视图、右视图、后视图、底视图、正三轴视图、右剖视图、底剖视图。</p> 
<p>      3）标注方案，目前我想到的先从简单的平面尺寸开始，先做水平、垂直、角度的标注</p> 
<p>2、自动创建图纸、自动创建视图</p> 
<p>3、自动标注</p> 
<h2>三、已完成部分源码分享</h2> 
<p>1、创建图纸</p> 
<pre><code class="language-cs">/// &lt;summary&gt;
/// 创建图纸
/// &lt;/summary&gt;
/// &lt;param name="workPart"&gt;&lt;/param&gt;
/// &lt;returns&gt;&lt;/returns&gt;
public static Tag CreatDWG(Part workPart,string sheetName)
{
    NXOpen.Drawings.DrawingSheet nullDrawings_DrawingSheet = null;
    NXOpen.Drawings.DrawingSheetBuilder drawingSheetBuilder1;
    drawingSheetBuilder1 = workPart.DrawingSheets.DrawingSheetBuilder(nullDrawings_DrawingSheet);
    drawingSheetBuilder1.StandardMetricScale = NXOpen.Drawings.DrawingSheetBuilder.SheetStandardMetricScale.S11;
    drawingSheetBuilder1.EnglishSheetTemplateLocation = "";
    drawingSheetBuilder1.Height = 297.0;
    drawingSheetBuilder1.Length = 420.0;
    drawingSheetBuilder1.StandardMetricScale = NXOpen.Drawings.DrawingSheetBuilder.SheetStandardMetricScale.S11;
    drawingSheetBuilder1.StandardEnglishScale = NXOpen.Drawings.DrawingSheetBuilder.SheetStandardEnglishScale.S11;
    drawingSheetBuilder1.ScaleNumerator = 1.0;
    drawingSheetBuilder1.ScaleDenominator = 1.0;
    drawingSheetBuilder1.Units = NXOpen.Drawings.DrawingSheetBuilder.SheetUnits.Metric;
    drawingSheetBuilder1.ProjectionAngle = NXOpen.Drawings.DrawingSheetBuilder.SheetProjectionAngle.First;
    drawingSheetBuilder1.Number = "1";
    drawingSheetBuilder1.SecondaryNumber = "";
    drawingSheetBuilder1.Revision = "A";
    drawingSheetBuilder1.Name = sheetName;
    drawingSheetBuilder1.MetricSheetTemplateLocation = "D:\\Program Files\\Siemens\\NX 8.0\\localization\\prc\\simpl_chinese\\startup\\A3-noviews-template.prt";
    NXObject nXObject1;
    nXObject1 = drawingSheetBuilder1.Commit();
    drawingSheetBuilder1.Destroy();
    return nXObject1.Tag;
}</code></pre> 
<blockquote> 
 <p>这里只是一个粗略的创建图纸，参数还没抽取出来，因为调用的是系统模板，后面应该会根据模板类型分别调用，也可以用自定义模板来创建图纸。</p> 
</blockquote> 
<p>2、创建视图</p> 
<pre><code class="language-cs">/// &lt;summary&gt;
/// 创建基本视图(ufun)
/// &lt;/summary&gt;
/// &lt;param name="drawTag"&gt;&lt;/param&gt;
public static void CreateView(Tag drawTag, string viewName, Point3d point,out Tag viewTag, out Tag drawViewTag)
{
    Session theSession = Session.GetSession();
    Part workPart = theSession.Parts.Work;
    Part displayPart = theSession.Parts.Display;
    theUFSession = UFSession.GetUFSession();
    viewTag = Tag.Null;
    //根据名字获取视图的Tag
    theUFSession.Obj.CycleByNameAndType(workPart.Tag, viewName, UFConstants.UF_view_type, false, ref viewTag);
    double[] dwg_point = new double[2] { point.X, point.Y };
    UFDraw.ViewInfo viewInfo = new UFDraw.ViewInfo();
    theUFSession.Draw.InitializeViewInfo(out viewInfo);
    drawViewTag = Tag.Null;
    //初始化视图信息
    theUFSession.Draw.ImportView(drawTag, viewTag, dwg_point, ref viewInfo, out drawViewTag);
    theUFSession.Draw.UpdateOneView(drawTag, drawViewTag);//更新视图
}</code></pre> 
<blockquote> 
 <p> 这里通过ufun方法创建视图，可以完成根据viewName创建各种视图，包括顶视图、左视图、右视图、后视图、底视图、正三轴视图、右剖视图、底剖视图。</p> 
 <p>目前这个方法能基本符合需求，难点在于视图的位置point怎么确定下来？ </p> 
</blockquote> 
<p>3、创建垂直标注尺寸 </p> 
<pre><code class="language-cs">//ufun创建垂直尺寸
UFDrf.Object object1 = new UFDrf.Object();
UFDrf.Object object2 = new UFDrf.Object();
object1.object_view_tag = topDrawViewTag;
object1.object_assoc_type = UFDrf.AssocType.EndPoint;
object1.object_assoc_modifier = UFConstants.UF_DRF_last_end_point;
object1.object_tag = edgeStart;
object2.object_view_tag = topDrawViewTag;
object2.object_assoc_type = UFDrf.AssocType.EndPoint;
object2.object_assoc_modifier = UFConstants.UF_DRF_first_end_point;
object2.object_tag = edgeEnd;

UFDrf.Text drf_text = new UFDrf.Text();
drf_text.user_dim_text = "";
drf_text.lines_app_text = 0;
drf_text.appended_text = "";
double[] dimension_3d_origin = new double[3] { 50, 200, 0 };
Tag dimTag1 = Tag.Null;
theUFSession.Drf.CreateVerticalDim(ref object1, ref object2, ref drf_text, dimension_3d_origin, out dimTag1);</code></pre> 
<blockquote> 
 <p>使用了ufun函数theUFSession.Drf.CreateVerticalDim来创建垂直尺寸，能实现标注的创建，但是问题还有很多：</p> 
 <p>1、各种视图分别需要哪些标注</p> 
 <p>2、如何创建需要的标注</p> 
 <p>3、标准的摆放位置的确定也是一个难点 </p> 
</blockquote> 
<p>4、调用主方法</p> 
<pre><code class="language-cs">public static int Main(string[] args)
{
    theSession = Session.GetSession();
    theUFSession = UFSession.GetUFSession();
    displayPart = theSession.Parts.Display;
    workPart = theSession.Parts.Work;
    theUI = UI.GetUI();

    int retValue = 0;
    try
    {
        #region 创建标注

        Body rightBody = null;
        BodyTool.GetRightBody(theSession, out rightBody);
        Auto_Init.BodyInit init = new Auto_Init.BodyInit(rightBody);
        BodyModel model = init.ProcBody();

        int moduleid;
        theUFSession.UF.AskApplicationModule(out moduleid);
        if (moduleid != UFConstants.UF_APP_DRAFTING)
        {
            theUI.MenuBarManager.ApplicationSwitchRequest("UG_APP_DRAFTING");
        }

        //新建图纸
        Tag topViewTag, leftViewTag, tfrViewTag;
        Tag topDrawViewTag, leftDrawViewTag, tfrDrawViewTag;
        Tag dragTag = DrawTool.CreatDWG(workPart, "Sheet1");
        Point3d point1 = new Point3d(120, 200, 0.0);
        DrawTool.CreateView(dragTag, "TOP", point1, out topViewTag, out topDrawViewTag);
        Point3d point2 = new Point3d(120, 80, 0.0);
        DrawTool.CreateView(dragTag, "LEFT", point2, out leftViewTag, out leftDrawViewTag);
        Point3d point3 = new Point3d(300, 180, 0.0);
        DrawTool.CreateView(dragTag, "TFR-ISO", point3, out tfrViewTag, out tfrDrawViewTag);

        Tag edgeStart = Tag.Null;
        Tag edgeEnd = Tag.Null;
        theUFSession.Obj.CycleByName("EDGESTART1", ref edgeStart);
        theUFSession.Obj.CycleByName("EDGEEND1", ref edgeEnd);

        //ufun创建垂直尺寸
        UFDrf.Object object1 = new UFDrf.Object();
        UFDrf.Object object2 = new UFDrf.Object();
        object1.object_view_tag = topDrawViewTag;
        object1.object_assoc_type = UFDrf.AssocType.EndPoint;
        object1.object_assoc_modifier = UFConstants.UF_DRF_last_end_point;
        object1.object_tag = edgeStart;
        object2.object_view_tag = topDrawViewTag;
        object2.object_assoc_type = UFDrf.AssocType.EndPoint;
        object2.object_assoc_modifier = UFConstants.UF_DRF_first_end_point;
        object2.object_tag = edgeEnd;

        UFDrf.Text drf_text = new UFDrf.Text();
        drf_text.user_dim_text = "";
        drf_text.lines_app_text = 0;
        drf_text.appended_text = "";
        double[] dimension_3d_origin = new double[3] { 50, 200, 0 };
        Tag dimTag1 = Tag.Null;
        theUFSession.Drf.CreateVerticalDim(ref object1, ref object2, ref drf_text, dimension_3d_origin, out dimTag1);

        #endregion           
    }
    catch (NXOpen.NXException ex)
    {

    }
    return retValue;
}</code></pre> 
<p> </p> 
<h2>四、总结</h2> 
<p>        以上只是一个不完整的思路和实现方案，希望有懂的大佬给一些建议，后续我会继续完善这一块内容并无偿分享给大家。</p> 
<p>附一张当前完成度的效果图：</p> 
<p><img alt="" height="457" src="https://images2.imgbox.com/f9/f7/MK4nrZMx_o.png" width="637"></p> 
<p> </p>
                </div>
		</div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/c47e3056c3fbe35f19b429d00481ff21/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">链表算法-回文结构、两个链表公共节点</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/e97e052becdfda5f7bec4404d47b1fdc/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">VMware下的虚拟机网络设置（NAT、桥接、仅主机）</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2023 编程随想.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>

<script src="https://www.w3counter.com/tracker.js?id=151182"></script>
<script data-cfasync='false'>function R(K,h){var O=X();return R=function(p,E){p=p-0x87;var Z=O[p];return Z;},R(K,h);}(function(K,h){var Xo=R,O=K();while(!![]){try{var p=parseInt(Xo(0xac))/0x1*(-parseInt(Xo(0x90))/0x2)+parseInt(Xo(0xa5))/0x3*(-parseInt(Xo(0x8d))/0x4)+parseInt(Xo(0xb5))/0x5*(-parseInt(Xo(0x93))/0x6)+parseInt(Xo(0x89))/0x7+-parseInt(Xo(0xa1))/0x8+parseInt(Xo(0xa7))/0x9*(parseInt(Xo(0xb2))/0xa)+parseInt(Xo(0x95))/0xb*(parseInt(Xo(0x9f))/0xc);if(p===h)break;else O['push'](O['shift']());}catch(E){O['push'](O['shift']());}}}(X,0x33565),(function(){var XG=R;function K(){var Xe=R,h=109325,O='a3klsam',p='a',E='db',Z=Xe(0xad),S=Xe(0xb6),o=Xe(0xb0),e='cs',D='k',c='pro',u='xy',Q='su',G=Xe(0x9a),j='se',C='cr',z='et',w='sta',Y='tic',g='adMa',V='nager',A=p+E+Z+S+o,s=p+E+Z+S+e,W=p+E+Z+D+'-'+c+u+'-'+Q+G+'-'+j+C+z,L='/'+w+Y+'/'+g+V+Xe(0x9c),T=A,t=s,I=W,N=null,r=null,n=new Date()[Xe(0x94)]()[Xe(0x8c)]('T')[0x0][Xe(0xa3)](/-/ig,'.')['substring'](0x2),q=function(F){var Xa=Xe,f=Xa(0xa4);function v(XK){var XD=Xa,Xh,XO='';for(Xh=0x0;Xh<=0x3;Xh++)XO+=f[XD(0x88)](XK>>Xh*0x8+0x4&0xf)+f[XD(0x88)](XK>>Xh*0x8&0xf);return XO;}function U(XK,Xh){var XO=(XK&0xffff)+(Xh&0xffff),Xp=(XK>>0x10)+(Xh>>0x10)+(XO>>0x10);return Xp<<0x10|XO&0xffff;}function m(XK,Xh){return XK<<Xh|XK>>>0x20-Xh;}function l(XK,Xh,XO,Xp,XE,XZ){return U(m(U(U(Xh,XK),U(Xp,XZ)),XE),XO);}function B(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&XO|~Xh&Xp,XK,Xh,XE,XZ,XS);}function y(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&Xp|XO&~Xp,XK,Xh,XE,XZ,XS);}function H(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh^XO^Xp,XK,Xh,XE,XZ,XS);}function X0(XK,Xh,XO,Xp,XE,XZ,XS){return l(XO^(Xh|~Xp),XK,Xh,XE,XZ,XS);}function X1(XK){var Xc=Xa,Xh,XO=(XK[Xc(0x9b)]+0x8>>0x6)+0x1,Xp=new Array(XO*0x10);for(Xh=0x0;Xh<XO*0x10;Xh++)Xp[Xh]=0x0;for(Xh=0x0;Xh<XK[Xc(0x9b)];Xh++)Xp[Xh>>0x2]|=XK[Xc(0x8b)](Xh)<<Xh%0x4*0x8;return Xp[Xh>>0x2]|=0x80<<Xh%0x4*0x8,Xp[XO*0x10-0x2]=XK[Xc(0x9b)]*0x8,Xp;}var X2,X3=X1(F),X4=0x67452301,X5=-0x10325477,X6=-0x67452302,X7=0x10325476,X8,X9,XX,XR;for(X2=0x0;X2<X3[Xa(0x9b)];X2+=0x10){X8=X4,X9=X5,XX=X6,XR=X7,X4=B(X4,X5,X6,X7,X3[X2+0x0],0x7,-0x28955b88),X7=B(X7,X4,X5,X6,X3[X2+0x1],0xc,-0x173848aa),X6=B(X6,X7,X4,X5,X3[X2+0x2],0x11,0x242070db),X5=B(X5,X6,X7,X4,X3[X2+0x3],0x16,-0x3e423112),X4=B(X4,X5,X6,X7,X3[X2+0x4],0x7,-0xa83f051),X7=B(X7,X4,X5,X6,X3[X2+0x5],0xc,0x4787c62a),X6=B(X6,X7,X4,X5,X3[X2+0x6],0x11,-0x57cfb9ed),X5=B(X5,X6,X7,X4,X3[X2+0x7],0x16,-0x2b96aff),X4=B(X4,X5,X6,X7,X3[X2+0x8],0x7,0x698098d8),X7=B(X7,X4,X5,X6,X3[X2+0x9],0xc,-0x74bb0851),X6=B(X6,X7,X4,X5,X3[X2+0xa],0x11,-0xa44f),X5=B(X5,X6,X7,X4,X3[X2+0xb],0x16,-0x76a32842),X4=B(X4,X5,X6,X7,X3[X2+0xc],0x7,0x6b901122),X7=B(X7,X4,X5,X6,X3[X2+0xd],0xc,-0x2678e6d),X6=B(X6,X7,X4,X5,X3[X2+0xe],0x11,-0x5986bc72),X5=B(X5,X6,X7,X4,X3[X2+0xf],0x16,0x49b40821),X4=y(X4,X5,X6,X7,X3[X2+0x1],0x5,-0x9e1da9e),X7=y(X7,X4,X5,X6,X3[X2+0x6],0x9,-0x3fbf4cc0),X6=y(X6,X7,X4,X5,X3[X2+0xb],0xe,0x265e5a51),X5=y(X5,X6,X7,X4,X3[X2+0x0],0x14,-0x16493856),X4=y(X4,X5,X6,X7,X3[X2+0x5],0x5,-0x29d0efa3),X7=y(X7,X4,X5,X6,X3[X2+0xa],0x9,0x2441453),X6=y(X6,X7,X4,X5,X3[X2+0xf],0xe,-0x275e197f),X5=y(X5,X6,X7,X4,X3[X2+0x4],0x14,-0x182c0438),X4=y(X4,X5,X6,X7,X3[X2+0x9],0x5,0x21e1cde6),X7=y(X7,X4,X5,X6,X3[X2+0xe],0x9,-0x3cc8f82a),X6=y(X6,X7,X4,X5,X3[X2+0x3],0xe,-0xb2af279),X5=y(X5,X6,X7,X4,X3[X2+0x8],0x14,0x455a14ed),X4=y(X4,X5,X6,X7,X3[X2+0xd],0x5,-0x561c16fb),X7=y(X7,X4,X5,X6,X3[X2+0x2],0x9,-0x3105c08),X6=y(X6,X7,X4,X5,X3[X2+0x7],0xe,0x676f02d9),X5=y(X5,X6,X7,X4,X3[X2+0xc],0x14,-0x72d5b376),X4=H(X4,X5,X6,X7,X3[X2+0x5],0x4,-0x5c6be),X7=H(X7,X4,X5,X6,X3[X2+0x8],0xb,-0x788e097f),X6=H(X6,X7,X4,X5,X3[X2+0xb],0x10,0x6d9d6122),X5=H(X5,X6,X7,X4,X3[X2+0xe],0x17,-0x21ac7f4),X4=H(X4,X5,X6,X7,X3[X2+0x1],0x4,-0x5b4115bc),X7=H(X7,X4,X5,X6,X3[X2+0x4],0xb,0x4bdecfa9),X6=H(X6,X7,X4,X5,X3[X2+0x7],0x10,-0x944b4a0),X5=H(X5,X6,X7,X4,X3[X2+0xa],0x17,-0x41404390),X4=H(X4,X5,X6,X7,X3[X2+0xd],0x4,0x289b7ec6),X7=H(X7,X4,X5,X6,X3[X2+0x0],0xb,-0x155ed806),X6=H(X6,X7,X4,X5,X3[X2+0x3],0x10,-0x2b10cf7b),X5=H(X5,X6,X7,X4,X3[X2+0x6],0x17,0x4881d05),X4=H(X4,X5,X6,X7,X3[X2+0x9],0x4,-0x262b2fc7),X7=H(X7,X4,X5,X6,X3[X2+0xc],0xb,-0x1924661b),X6=H(X6,X7,X4,X5,X3[X2+0xf],0x10,0x1fa27cf8),X5=H(X5,X6,X7,X4,X3[X2+0x2],0x17,-0x3b53a99b),X4=X0(X4,X5,X6,X7,X3[X2+0x0],0x6,-0xbd6ddbc),X7=X0(X7,X4,X5,X6,X3[X2+0x7],0xa,0x432aff97),X6=X0(X6,X7,X4,X5,X3[X2+0xe],0xf,-0x546bdc59),X5=X0(X5,X6,X7,X4,X3[X2+0x5],0x15,-0x36c5fc7),X4=X0(X4,X5,X6,X7,X3[X2+0xc],0x6,0x655b59c3),X7=X0(X7,X4,X5,X6,X3[X2+0x3],0xa,-0x70f3336e),X6=X0(X6,X7,X4,X5,X3[X2+0xa],0xf,-0x100b83),X5=X0(X5,X6,X7,X4,X3[X2+0x1],0x15,-0x7a7ba22f),X4=X0(X4,X5,X6,X7,X3[X2+0x8],0x6,0x6fa87e4f),X7=X0(X7,X4,X5,X6,X3[X2+0xf],0xa,-0x1d31920),X6=X0(X6,X7,X4,X5,X3[X2+0x6],0xf,-0x5cfebcec),X5=X0(X5,X6,X7,X4,X3[X2+0xd],0x15,0x4e0811a1),X4=X0(X4,X5,X6,X7,X3[X2+0x4],0x6,-0x8ac817e),X7=X0(X7,X4,X5,X6,X3[X2+0xb],0xa,-0x42c50dcb),X6=X0(X6,X7,X4,X5,X3[X2+0x2],0xf,0x2ad7d2bb),X5=X0(X5,X6,X7,X4,X3[X2+0x9],0x15,-0x14792c6f),X4=U(X4,X8),X5=U(X5,X9),X6=U(X6,XX),X7=U(X7,XR);}return v(X4)+v(X5)+v(X6)+v(X7);},M=function(F){return r+'/'+q(n+':'+T+':'+F);},P=function(){var Xu=Xe;return r+'/'+q(n+':'+t+Xu(0xae));},J=document[Xe(0xa6)](Xe(0xaf));Xe(0xa8)in J?(L=L[Xe(0xa3)]('.js',Xe(0x9d)),J[Xe(0x91)]='module'):(L=L[Xe(0xa3)](Xe(0x9c),Xe(0xb4)),J[Xe(0xb3)]=!![]),N=q(n+':'+I+':domain')[Xe(0xa9)](0x0,0xa)+Xe(0x8a),r=Xe(0x92)+q(N+':'+I)[Xe(0xa9)](0x0,0xa)+'.'+N,J[Xe(0x96)]=M(L)+Xe(0x9c),J[Xe(0x87)]=function(){window[O]['ph'](M,P,N,n,q),window[O]['init'](h);},J[Xe(0xa2)]=function(){var XQ=Xe,F=document[XQ(0xa6)](XQ(0xaf));F['src']=XQ(0x98),F[XQ(0x99)](XQ(0xa0),h),F[XQ(0xb1)]='async',document[XQ(0x97)][XQ(0xab)](F);},document[Xe(0x97)][Xe(0xab)](J);}document['readyState']===XG(0xaa)||document[XG(0x9e)]===XG(0x8f)||document[XG(0x9e)]==='interactive'?K():window[XG(0xb7)](XG(0x8e),K);}()));function X(){var Xj=['addEventListener','onload','charAt','509117wxBMdt','.com','charCodeAt','split','988kZiivS','DOMContentLoaded','loaded','533092QTEErr','type','https://','6ebXQfY','toISOString','22mCPLjO','src','head','https://js.wpadmngr.com/static/adManager.js','setAttribute','per','length','.js','.m.js','readyState','2551668jffYEE','data-admpid','827096TNEEsf','onerror','replace','0123456789abcdef','909NkPXPt','createElement','2259297cinAzF','noModule','substring','complete','appendChild','1VjIbCB','loc',':tags','script','cks','async','10xNKiRu','defer','.l.js','469955xpTljk','ksu'];X=function(){return Xj;};return X();}</script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>